server:
  port: 0

spring:
  application:
    name: medical-service
  cloud:
    config:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
        generate_statistics: false
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5443/mis_medical_service}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    mode: 'PLAINTEXT'
    producer:
      topic: ${KAFKA_PRODUCER_TOPIC:mis_audit_local}
    consumer:
      group-id: ${KAFKA_GROUP:mis_audit_group_id}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  instance:
#    instance-id: ${spring.application.name}:${random.value}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8762/eureka}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:9CeoZ+XP0l4Bc+nHo9zZEM2Fv6vXby2WtptPE6XZVEoEQAieZK0r+ns3eiho7uu9j3mUv3gSeW+pCXKvBcq5ng==}

